"""缓存感知的上下文编译、持久化与压缩能力。"""

from memoli_agent.agent.context_management.compaction import (
    CompactionError,
    TaskAwareCompactor,
)
from memoli_agent.agent.context_management.compiler import (
    ContextBudgetExhausted,
    ContextCompactionCircuitOpen,
    ContextCompiler,
    ContextCompilerSettings,
    ContextSnapshotInvalidated,
)
from memoli_agent.agent.context_management.cross_turn import (
    CommittedMessage,
    CommittedTurn,
    CommittedTurnStore,
    ContextSource,
    InProcessTurnSource,
    LegacyTurnSource,
    PreviewIntegrityLookup,
    RestorationLevel,
    TrajectoryContextSource,
    build_envelope,
    verify_turn_previews,
)
from memoli_agent.agent.context_management.models import (
    CompactionPlan,
    ContextArchive,
    ContextBlock,
    ContextBudget,
    ContextCompilation,
    ContextDiagnostic,
    ContextSnapshot,
    FrozenToolPreview,
    LayerBudget,
    OutboxEvent,
    TurnEnvelope,
    normalized_cache_usage,
)
from memoli_agent.agent.context_management.preview import ToolResultPreviewer
from memoli_agent.agent.context_management.repository import (
    ContextStateError,
    ContextStateRepository,
    InMemoryContextStateRepository,
    SQLiteContextStateRepository,
)
from memoli_agent.agent.context_management.tokens import (
    ConservativeTokenEstimator,
    TokenEstimator,
    register_tokenizer_adapter,
    resolve_token_estimator,
)

__all__ = [
    "CommittedMessage",
    "CommittedTurn",
    "CommittedTurnStore",
    "CompactionError",
    "CompactionPlan",
    "ConservativeTokenEstimator",
    "ContextArchive",
    "ContextBudgetExhausted",
    "ContextBlock",
    "ContextBudget",
    "ContextCompilation",
    "ContextCompiler",
    "ContextCompactionCircuitOpen",
    "ContextCompilerSettings",
    "ContextDiagnostic",
    "ContextSource",
    "ContextSnapshot",
    "ContextSnapshotInvalidated",
    "FrozenToolPreview",
    "InProcessTurnSource",
    "LegacyTurnSource",
    "PreviewIntegrityLookup",
    "RestorationLevel",
    "TokenEstimator",
    "TaskAwareCompactor",
    "ToolResultPreviewer",
    "TrajectoryContextSource",
    "ContextStateError",
    "ContextStateRepository",
    "InMemoryContextStateRepository",
    "LayerBudget",
    "OutboxEvent",
    "TurnEnvelope",
    "normalized_cache_usage",
    "register_tokenizer_adapter",
    "resolve_token_estimator",
    "SQLiteContextStateRepository",
    "build_envelope",
    "verify_turn_previews",
]
